export const APPOINTMENT_READER = Symbol('APPOINTMENT_READER');
export const APPOINTMENT_WRITER = Symbol('APPOINTMENT_WRITER');
export const APPOINTMENT_AVAILABLE_SLOTS_READER = Symbol(
  'APPOINTMENT_AVAILABLE_SLOTS_READER',
);
export const APPOINTMENT_SCHEDULING_OPTIONS_READER = Symbol(
  'APPOINTMENT_SCHEDULING_OPTIONS_READER',
);
