export const INBOX_CONVERSATION_READER = Symbol('INBOX_CONVERSATION_READER');

export const INBOX_CONVERSATION_CONTROL_WRITER = Symbol(
  'INBOX_CONVERSATION_CONTROL_WRITER',
);

export const INBOX_DEVELOPMENT_MESSAGE_WRITER = Symbol(
  'INBOX_DEVELOPMENT_MESSAGE_WRITER',
);
